apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: ivolve
spec:
  selector:
    app: py-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30010  
      targetPort: 5000

